---
- include_role:
    name: prepd-cli/project
  vars:
    spec:
      project_dir: '{{ project_dir }}'
  when: user_action is defined and user_action == 'new'

- include_tasks: ops.yml
  when: user_action is not defined or user_action != 'new'
