#!/usr/bin/env ansible-playbook
# NOTE: run with -K to prompt for sudo password
# NOTE: the order of the playbook is important. Configure developer environment before installing tooling
# as roles installed after that often depend on the shell type which is zsh in the case of yadr
---
- import_playbook: developer.yml

- name: Install base packages on developer machine that will be hosting VMs
  hosts: prepd
  tasks:
    - include_role:
        name: prepd/machine-config
      vars:
        role_spec: {}

    # NOTE: virtualbox is first b/c it will fail when installed on Mac. See:
    - include_role:
        name: prepd/virtualbox

    - include_role:
        name: prepd/vagrant/setup

    - include_role:
        name: prepd/prepd-tools
      vars:
        role_spec: {}

    - include_role:
        name: prepd/host-install
      vars:
        role_spec:
          mac:
            - dropbox
            - evernote
            - firefox
            - google-chrome
            # - insomniax
            - iterm2
            - kindle
            - postman
            - skype
            - slack
            - spotify
            - transmission
            - vlc
            - whatsapp
          debian:
            - google-chrome-stable
