---
- name: 'Clone prepd repositories'
  git:
    repo: '{{ item.repo }}'
    dest: '{{ ansible_env.HOME }}/.ansible/roles/{{ item.dest }}'
  with_items:
    - repo: git@github.com:rjayroach/prepd-roles.git
      dest: prepd
    - repo: git@github.com:rjayroach/packer.git
      dest: packer
    - repo: git@github.com:rjayroach/terraplate-playbooks.git
      dest: terraplate

- name: 'Create {{ ansible_env.HOME }}/.prepd'
  file:
    path: '{{ ansible_env.HOME }}/.prepd'
    state: directory

- name: Template prepd settings
  template:
    src: settings.yml
    dest: '{{ ansible_env.HOME }}/.prepd/settings.yml'

- name: Create the host-install.yml playbook
  copy:
    src: host-install.yml
    dest: '{{ playbook_dir }}/host-install.yml'
    mode: 0755
